# Generated by Django 4.2.7 on 2023-11-11 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=100)),
                ('gdescription', models.TextField()),
                ('gprofile', models.ImageField(blank=True, null=True, upload_to='group_profiles/')),
                ('gtag', models.CharField(choices=[('Untitled', 'Untitled'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red')], default='Untitled', max_length=20)),
                ('gcreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to=settings.AUTH_USER_MODEL)),
                ('gmembers', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('pcontent', models.TextField()),
                ('ptag', models.CharField(choices=[('Untitled', 'Untitled'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red')], default='Untitled', max_length=20)),
                ('pcreated_on', models.DateTimeField(auto_now_add=True)),
                ('pauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to=settings.AUTH_USER_MODEL)),
                ('pgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
