# Generated by Django 4.2.7 on 2023-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_account_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='account_UID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
