# Generated by Django 4.2.7 on 2023-11-19 13:13

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userinfo_account_uid_alter_userinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.URLField(default='-', validators=[django.core.validators.URLValidator(), user.models.validate_facebook_or_instagram]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='user/templates/profile/p_df.jpg', upload_to='user/templates/profile/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sir_name',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
